### ISSUE TITLE
[run error] No OpKernel was registered to support Op 'PropTcfg' with these attrs

### ISSUE THREAD

**Issue by nevin007** [TencentYoutuResearch/ActionDetection-DBG#2]
Hi, 
I had follow the instructions to installed tf1.9.0 and python3.6, and compiled "Proposal Feature Generation Layer" successfully, which generate "prop_tcfg.so". but when run "bash auto_run.sh", following errors were occured:

loading config file: ./config.yaml
loading config file: ./config.yaml
2019-11-23 17:13:54.840138: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-11-23 17:13:54.841548: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Runing DBG model ...
  0%|                                                                                                                                                                               | 0/296 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/anaconda2/envs/tf19/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/anaconda2/envs/tf19/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/anaconda2/envs/tf19/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: **No OpKernel was registered to support Op 'PropTcfg' with these attrs.**  Registered devices: [CPU], Registered kernels:
  device='GPU'; T in [DT_FLOAT]

	 [[Node: model/PropTcfg = PropTcfg[T=DT_FLOAT, center_num=16, end_num=8, mode=0, start_num=8](model/strided_slice)]]

It seems like the Op 'PropTcfg' was not registered correctly, but How can I fix it? Thank you!

**Comment by linchuming** [comment]
Hi, our Op 'PropTcfg' only supports GPU device now.
So please use GPU to run our code and use tensorflow-gpu instead of tensorflow.

**Comment by nevin007** [comment]
> Hi, our Op 'PropTcfg' only supports GPU device now.
> So please use GPU to run our code and use tensorflow-gpu instead of tensorflow.

It works, Thank you very much! Good job!
